apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratelimitapi

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratelimitapi
    spec:
      containers:
      - name: ratelimitapi
        image: jit2600/ratelimitapi:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
  
