apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimitapi
  labels:
    app: ratelimitapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ratelimitapi
  template:
    metadata:
      labels:
        app: ratelimitapi
    spec:
      containers:
      - name: ratelimitapi
        image: jit2600/ratelimitapi:latest
        ports:
        - containerPort: 5000
